services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-teste-app
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: api-teste-db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123456789

  postgres:
    image: postgres:latest
    container_name: api-teste-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: api-teste-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
